config/routes.rb
Rails.application.routes.draw do

  resources :employees

  root 'employees#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :edit, :update, :destroy]

  def index
    @employees = Employee.all.order("Created_at DESC")
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end

  def show

  end

  def edit

  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render 'edit'
    end

  end

  def destroy
    if @employee.destroy
      redirect_to employees_path
    else
      redirect_to @employee
    end

  end

  private

    def employee_params
      params.require(:employee).permit(:name, :description)
    end

    def find_employee
      @employee = Employee.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= simple_form_for @employee do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.button :submit %>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee's Information</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<h1>Employees</h1>
<br>
<% @employees.each do |employee| %>
  <h3><%= link_to employee.name, employee %></h3>

<% end %>

app/views/employees/new.html.erb
<h1>Add new Employee</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<h1>Employee's Information</h1>
<h2>Name: <%= @employee.name %></h2>
<h3>Description: <%= @employee.description %></h3>

<br>
<%= link_to 'Edit', edit_employee_path(@employee) %>
<%= link_to 'Delete', @employee, method: :delete, data: { confirm: "Are you sure?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Performance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>